### ISSUE TITLE
go mod vendor is failed in operator repo

### ISSUE THREAD

**Issue by clyang82** [observatorium/operator#16]
`go mod vendor` is failed with
```
github.com/observatorium/operator imports
	github.com/brancz/locutus imports
	k8s.io/client-go/kubernetes imports
	k8s.io/client-go/discovery imports
	github.com/googleapis/gnostic/OpenAPIv2: module github.com/googleapis/gnostic@latest found (v0.5.1), but does not contain package github.com/googleapis/gnostic/OpenAPIv2
github.com/observatorium/operator imports
	github.com/brancz/locutus imports
	k8s.io/client-go/kubernetes imports
	k8s.io/client-go/kubernetes/typed/auditregistration/v1alpha1 imports
	k8s.io/api/auditregistration/v1alpha1: module k8s.io/api@latest found (v0.19.2), but does not contain package k8s.io/api/auditregistration/v1alpha1
```

`go mod vendor` can be running successfully in `55feecd281df6447fb676707b28c384d841f86c3`. 
I think It is broken by https://github.com/observatorium/operator/commit/fa34913e2cbb6a90c6a40437ead62cc36390da3f

the Downstream build requires `go mod vendor` can be able to run successfully so that cachito can fetch the correct dependencies to build locutus.

FYI @metalmatze @squat

**Comment by metalmatze** [comment]
Seems like that's the case indeed. Happy to get PRs that fix this situation.
Let me know if you need help.
