### ISSUE TITLE
Following docs/deploy-operator.md does not result in successful installation due to missing / outdated content

### ISSUE THREAD

**Issue by matej-g** [observatorium/operator#75]
As a first time user, I've been trying to install the latest `master` version of the operator on my local machine (in KinD) for testing purposes. However, after following the instructions in `docs/deploy-operator.md`, I was not able to finish the installation successfully without undertaking further steps. In particular, the issues I discovered:

- Applying `example/manifest/observatorium.yaml` results in validation error:
  ```
  error: error validating "https://raw.githubusercontent.com/observatorium/operator/master/example/manifests/observatorium.yaml": error validating data: [ValidationError(Observatorium.spec): unknown field "apiQuery" in io.observatorium.core.v1alpha1.Observatorium.spec, ValidationError(Observatorium.spec.securityContext): unknown field "fsGroup" in io.observatorium.core.v1alpha1.Observatorium.spec.securityContext]; if you choose to ignore these errors, turn validation off with --validate=false
  ```
  since it includes unknown fields `apiQuery` (removed in https://github.com/observatorium/operator/pull/9) and `fsGroup` (which does not appear to be included in `securityContext`, but rather in `podSecurityContext`); a possible resolution via https://github.com/observatorium/operator/pull/66.

- Observatorium API pod fails to start due to missing secret `observatorium-xyz-tls` and missing configmaps `observatorium-xyz-tls` and `test-ca-tls` - these are not created in the process / user is not instructed to create these.

-  The [example CR](https://github.com/observatorium/operator/blob/2090181136dbc0b6468da3ae22fb6858ee5da9fd/example/manifests/observatorium.yaml#L40) seems to expect Dex to be available as an issuer, however user is not instructed to deploy it.

- For post-installation test, the observatorium up metrics job has wrong manifest link (should be https://raw.githubusercontent.com/observatorium/observatorium/main/configuration/tests/manifests/observatorium-up-metrics.yaml instead of https://raw.githubusercontent.com/observatorium/deployments/master/tests/manifests/observatorium-up-metrics.yaml). 

If possible, these issues should be addressed and content updated, to make the deployment instructions clearer for users.

**Comment by makeittotop** [comment]
Any updates on this?
