### ISSUE TITLE
All checks have failed

### ISSUE THREAD

**Issue by clyang82** [observatorium/operator#79]
All checks have failed after merging the pull request.
I guessed it should be related with project settings.

refer to this ticket - https://discuss.circleci.com/t/git-github-com-permission-denied-publickey-on-repo-that-previously-worked/37763/4
> If you have received “git@github.com: Permission denied (publickey).” Please click “project settings” button, than “SSH keys”. Click to remove deploy key and than click “add deploy key” once again. Than you can click on “${project} deploy key”, it will navigate you to github. Your new deploy key should be visible on github project page.

> After that checkout will succeed.

@squat Can you help on? Thanks.

**Comment by squat** [comment]
Ack. I find it pretty bizarre that the key would suddenly become invalid. In any case, following these instructions fixed the issue; checking out code from circle CI is working once again and CI works :)
I think we would be well served moving to GitHub actions at some point to make the integration with CI better.

**Comment by clyang82** [comment]
Thanks @squat for your help to make ci works.
